katalog/urls.py
from django.urls import path
from katalog.views import show_katalog

app_name = 'katalog'

urlpatterns = [
    path('', show_katalog, name='show_katalog'),
]

project_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('example_app.urls')),
    path('katalog/', include('katalog.urls')),
    path('mywatchlist/', include('mywatchlist.urls')),
    path('todolist/', include('todolist.urls')),
]

todolist/urls.py
from django.urls import path
from todolist.views import *

app_name = 'todolist'

urlpatterns = [
    path('', show_todolist, name='show_todolist'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('create-task/', create_task, name='create_task'),
    path('change-task/<int:task_id>', change_task, name='change_task'),
    path('delete-task/<int:task_id>', delete_task, name='delete_task'),
    path('json/' , show_task_json, name='json'),
    path('add/', add_task_ajax, name='add'),
    path('delete/<int:task_id>', delete_task_ajax, name='delete'),
]

todolist/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from datetime import *

class Task(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    date = models.DateTimeField(default=datetime.now)
    description = models.TextField()
    is_finished = models.BooleanField(default=False)

todolist/forms.py
from django import forms;

class TaskForm(forms.Form):
    title = forms.CharField(max_length=200)
    description = forms.CharField(widget=forms.Textarea)

todolist/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.shortcuts import render
from django.shortcuts import render
from todolist.models import Task
from django.http import HttpResponse
from django.core import serializers
from django.shortcuts import redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.contrib.auth import authenticate, login, models;
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
from .forms import TaskForm
from django.views.decorators.csrf import csrf_exempt

@login_required(login_url='/todolist/login/')
def show_todolist(request):
    user = request.user
    context = {
        "todo_list": Task.objects.filter(user=user),
        "name": user.username,
    }
    return render(request, 'todolist.html', context=context)

@login_required(login_url='/todolist/login/')
def change_task(request, task_id):
    task = Task.objects.filter(user=request.user).get(id=task_id)
    task.is_finished = not task.is_finished
    task.save()
    return redirect('todolist:show_todolist')

@login_required(login_url='/todolist/login/')
def delete_task(request, task_id):
    task = Task.objects.filter(user=request.user).get(id=task_id)
    task.delete()
    return redirect('todolist:show_todolist')

@login_required(login_url='/todolist/login/')
def create_task(request):
    form = TaskForm();
    if request.method == "POST":
        form = TaskForm(request.POST)
        if form.is_valid():
            task = Task.objects.create(user=request.user, title=form.cleaned_data['title'], description=form.cleaned_data['description'])
            task.save()
            return redirect('todolist:show_todolist')
    return render(request, "create_task.html", {"form" : form})

@login_required(login_url='/todolist/login/')
def add_task_ajax(request):
    if request.method == 'POST':
        title = request.POST.get('title')
        description = request.POST.get('description')
        task = Task.objects.create(user=request.user, title=title, description=description)
        task.save()
        return HttpResponse(serializers.serialize('json', [task]), content_type='application/json')

    return HttpResponse("this cant be happening")

@login_required(login_url='/todolist/login/')
def show_task_json(request):
    if request.method == 'GET':
        tasks = Task.objects.filter(user=request.user)
        data = serializers.serialize('json', tasks)
        return HttpResponse(data, content_type='application/json')

    return HttpResponse("this cant be happening")

@login_required(login_url='/todolist/login/')
@csrf_exempt
def delete_task_ajax(request, task_id):
    if request.method == 'DELETE':
        task = Task.objects.filter(user=request.user).get(id=task_id)
        task.delete()
        return HttpResponse("Task deleted")

    return HttpResponse("this cant be happening")

# src: https://stackoverflow.com/questions/42546006/deleting-clearing-django-contrib-messages
def delete_messages(request):
    storage = messages.get_messages(request)
    for message in storage:
        pass

def register(request):
    form = UserCreationForm()
    form_errors = ""

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            delete_messages(request)
            form.save()
            messages.success(request, 'Akun telah berhasil dibuat!')
            return redirect('todolist:login')
        else:
            form_errors = form.errors
            form_errors = form_errors.get('password2')
            if form_errors:
                form_errors = form_errors.as_data()
                form_errors = "".join([str(error) for error in form_errors])
                form_errors = [errors for errors in form_errors.split("'") if '[' not in errors and ']' not in errors]
            else:
                messages.error(request, 'Akun gagal dibuat!')
    
    context = {'form':form, 'messages': form_errors}
    return render(request, 'register.html', context)

def login_user(request):
    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            response = HttpResponseRedirect(reverse("todolist:show_todolist")) # membuat response
            return response
        else:
            messages.info(request, 'Username atau Password salah!')
    context = {}
    return render(request, 'login.html', context)

def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('todolist:login'))
    return response

todolist/templates/create_task.html
{% extends 'base.html' %}

{% block meta %}
<title>Buat Task</title>
{% endblock meta %}

{% block content %}
<div class="login w-full flex flex-col items-center mt-14">
    <form method="POST" class="flex flex-col items-center mx-6 md:mx-4">
        <div class="flex flex-col gap-2 bg-white rounded-lg p-4 shadow-md">
            {% csrf_token %}

            <h1 class="font-bold text-xl text-gray-700 text-center">Create todo</h1>

            <div class="flex flex-col items-start gap-2 w-full">
                <label for="id_title">Title</label>
                <input class="input input-bordered w-full max-w-x" type="text" name="title" maxlength="50" required=""
                    id="id_title" />
            </div>
            <div class="flex flex-col items-start gap-2 w-full">
                <label for="id_description">Description</label>
                <textarea class="textarea textarea-bordered w-full" name="description" cols="40" rows="10"
                    maxlength="1000" required="" id="id_description"></textarea>
            </div>

        </div>
        <input class="btn w-[100px] mt-4" type="submit" name="submit" value="Create">
    </form>
</div>
{% endblock content %}

todolist/templates/login.html
{% extends 'base.html' %}

{% block meta %}
<title>Login</title>
{% endblock meta %}

{% block content %}

<div class="login flex flex-col justify-center items-center min-h-[90vh]">
    <div class="border rounded-2xl flex flex-col bg-base-300 text-center shadow-lg mx-6 md:mx-4">
        <h1 class="font-bold text-3xl p-4 bg-primary rounded-t-2xl ">Login</h1>

        <form method="POST" action="" class="flex flex-col justify-center items-center gap-2 p-4">
            {% csrf_token %}
            <div class="flex items-center gap-2">
                <label>Username: </label>
                <input type="text" name="username" placeholder="Username" class="form-condivol input w-full max-w-xs">
            </div>

            <div class="flex items-center gap-2">
                <label>Password: </label>
                <input type="password" name="password" placeholder="Password"
                    class="form-condivol input w-full max-w-xs">
            </div>

            <div>
                <label><input class="btn btn-primary" type="submit" value="Login"></label>
            </div>
        </form>

        {% if messages %}
        {% for message in messages %}
        <div class="alert alert-{{message.tags}} shadow-lg rounded-t-none rounded-b-2xl p-4 m-b-sm break-words">
            <div>
                {% if message.tags == "info" %}
                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24"
                    class="stroke-current flex-shrink-0 w-6 h-6">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                        d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"></path>
                </svg>
                {% elif message.tags == "success" %}
                <svg xmlns="http://www.w3.org/2000/svg" class="stroke-current flex-shrink-0 h-6 w-6" fill="none"
                    viewBox="0 0 24 24">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                        d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" />
                </svg>
                {% endif %}
                <span>{{ message }}</span>
            </div>
        </div>
        {% endfor %}
        {% endif %}

    </div>
    <div class=" text-center p-4 flex flex-col gap-2">
        <div class="font-semibold">Belum mempunyai akun?</div>
        <a href="{% url 'todolist:register' %}" class="btn bg-base-100 hover:bg-base:200">Buat Akun</a>
    </div>

</div>

{% endblock content %}

todolist/templates/register.html
{% extends 'base.html' %}

{% block meta %}
<title>Registrasi Akun</title>
{% endblock meta %}

{% block content %}

<div class="login flex flex-col justify-center items-center min-h-[90vh]">
    <div class="border rounded-2xl flex flex-col bg-base-300 text-center shadow-lg my-10 mx-4">

        <h1 class="font-bold lg:text-3xl p-4 bg-primary rounded-t-2xl">Formulir Registrasi</h1>

        <form method="POST" class="flex flex-col justify-center items-center gap-2 p-4">
            {% csrf_token %}
            <section class="flex flex-col w-full justify-center py-2 gap-4">
                <div class="flex flex-col">
                    <label for="id_username">Username: </label>
                    <input class="mt-1 border p-2 border-slate-700 rounded-md" type="text" name="username"
                        maxlength="150" autocapitalize="none" autocomplete="username" autofocus="" required=""
                        id="id_username">
                    <span class="helptext text-[12px]">Required. 150 characters or fewer. Letters, digits and @/./+/-/_
                        only.</span>
                </div>

                <div class="flex flex-col">
                    <label for="id_password1">Password:</label>
                    <input class="mt-1 border p-2 border-slate-700 rounded-md" type="password" name="password1"
                        autocomplete="new-password" required="" id="id_password1">
                    <span class="helptext text-[12px]">
                        <ul>
                            <li>
                                Your password can’t be too similar to your other personal information.
                            </li>
                            <li>
                                Your password must contain at least 8 characters.
                            </li>
                            <li>
                                Your password can’t be a commonly used password.
                            </li>
                            <li>
                                Your password can’t be entirely numeric.
                            </li>
                        </ul>
                    </span>
                </div>
                <div class="flex flex-col">
                    <label for="id_password2">Confirm Password:</label>
                    <input class="mt-1 border p-2 border-slate-700 rounded-md" type="password" name="password2"
                        autocomplete="new-password" required="" id="id_password2">
                    <span class="helptext text-[12px]">Enter the same password as before, for verification.</span>
                </div>
                <input class="btn mt-4 bg-gray-800" type="submit" value="Register"></td>
            </section>
        </form>

        {% if messages %}
        <div class="bg-error shadow-lg p-4 rounded-b-2xl m-b-sm break-words">
            <div class="flex items-center gap-2">
                <svg xmlns="http://www.w3.org/2000/svg" class="stroke-current flex-shrink-0 h-6 w-6" fill="none"
                    viewBox="0 0 24 24">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                        d="M10 14l2-2m0 0l2-2m-2 2l-2-2m2 2l2 2m7-2a9 9 0 11-18 0 9 9 0 0118 0z" />
                </svg>
                <span class="font-bold">Akun gagal dibuat!</span>
            </div>
            <ul class="flex flex-col items-start">
                {% for message in messages %}
                <li>{{ message }}</li>
                {% endfor %}
            </ul>
        </div>
        <div class="">
        </div>
        {% endif %}

    </div>
</div>

{% endblock content %}

todolist/templates/todolist.html
{% extends 'base.html' %}

{% block meta %}
<title>Todolist</title>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<!-- <script type="text/javascript"> window.CSRF_TOKEN = "{{ csrf_token }}"; </script> -->
<script>
    $(document).ready(function () {
        getTaskData();
        postTaskData();
    });

    function postTaskData() {
        $("form#add-task-form").submit(function (e) {
            e.preventDefault();
            var actionURL = e.currentTarget.action;
            var formData = $(this).serialize();
            $.ajax({
                url: actionURL,
                type: "POST",
                data: formData,
                dataType: "json",
                success: (data) => {
                    $("#close-task-modal").click();
                    $("#id_title").val("");
                    $("#id_description").val("");

                    // console.log(data);
                    appendTask(data[0]);
                },
                error: (error) => {
                    console.log(error);
                    alert("Error!");
                }
            });
        });
    }

    function getTaskData() {
        $.get("./json/", displayTask);
    }

    function displayTask(data) {
        const container = $("#task-container");
        container.empty();
        if (data.length > 0 && data[0].fields) {
            data.forEach(task => {
                appendTask(task);
            });
        } else {
            container.append(`
            <div id="no-task">
                <br>
                <p class="text-lg">
                    Kamu belum membuat todo list, silakan buat dengan mengklik tombol "Buat Todolist" di atas!
                </p>
                <br>
            </div>
            `);
        }
    }

    function appendTask(task) {
        const container = $("#task-container");
        $("#no-task").remove();
        taskFields = task.fields;
        container.append(`
        <div id="task-${task.pk}" class="card w-full md:w-4/5 lg:w-3/5 break-words bg-base-100 shadow-xl text-left glass mt-5 mb-5 transform duration-200 transition hover:scale-105">
            <div class="card-body">
                <div class="card-title justify-between items-center">
                    <div>${taskFields.title}</div>
                    <div>
                        ${taskFields.is_finished ? `
                            <div class="alert alert-success rounded-full p-1 animate-pulse">
                                <svg xmlns="http://www.w3.org/2000/svg" class="stroke-current flex-shrink-0 h-10 w-10"
                                    fill="none" viewBox="0 0 24 24">
                                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                        d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" />
                                </svg>
                            </div>
                            ` : `
                            <div class="alert alert-error shadow-lg rounded-full p-1 animate-pulse">
                                <svg xmlns="http://www.w3.org/2000/svg" class="stroke-current flex-shrink-0 h-10 w-10"
                                    fill="none" viewBox="0 0 24 24">
                                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                        d="M10 14l2-2m0 0l2-2m-2 2l-2-2m2 2l2 2m7-2a9 9 0 11-18 0 9 9 0 0118 0z" />
                                </svg>
                            </div>
                        `}
                    </div>
                </div>
                <div class="font-bold text-[12px]">${taskFields.date}</div>
                <p>${taskFields.description}</p>
                <div class="card-actions justify-end items-center">
                    <div class="flex w-full items-center justify-between">
                        <div class="flex items-center">
                            <a type="submit" name="submit" class="btn btn-ghost" onclick=deleteTask(${task.pk})><svg
                                    xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" class="w-8 h-8 text-white">
                                    <path fill="none" d="M0 0h24v24H0z" />
                                    <path
                                        d="M4 8h16v13a1 1 0 0 1-1 1H5a1 1 0 0 1-1-1V8zm2 2v10h12V10H6zm3 2h2v6H9v-6zm4 0h2v6h-2v-6zM7 5V3a1 1 0 0 1 1-1h8a1 1 0 0 1 1 1v2h5v2H2V5h5zm2-1v1h6V4H9z" />
                                </svg></a>
                        </div>
                        <div class="flex items-center ">
                            <a class="btn btn-primary" href="change-task/${task.pk}">Change
                                status</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        `);
    }

    function deleteTask(id) {
        $.ajax({
            url: `./delete/${id}`,
            type: "DELETE",
            success: (data) => {
                $(`#task-${data.task_id}`).remove();
                getTaskData();
            },
            error: (error) => {
                console.log(error);
                alert("Error!");
            }
        });
    }
</script>
{% endblock meta %}

{% block logout %}
<a class="btn btn-outline btn-error" href="{% url 'todolist:logout' %}">Logout</a>
{% endblock logout %}

{% block content %}
<div class="flex justify-center items-center flex-col gap-10 text-center p-1 w-full">

    <div class="flex flex-col justify-start items-center w-[90vw] md:w-4/5 lg:w-3/5 min-h-screen gap-4">
        <div class="flex justify-between items-center w-full">
            <h5 class="font-semibold text-xl p-5">Selamat datang, <span
                    class="text-3xl font-bold text-secondary">{{name}}!</span>
            </h5>
            <a class="btn btn-secondary" href="{% url 'todolist:create_task' %}">Buat Todolist</a>
        </div>
        <div class="text-2xl font-bold text-secondary"><span class="text-3xl text-primary">{{name}}</span>'s todolist:
        </div>
        <div id="task-container" class="w-full flex flex-col items-center"></div>
        <div></div>

        <!-- The button to open modal -->
        <label for="add-task-modal" class="btn modal-button">Add todo (ajax moment)</label>

        <!-- Put this part before </body> tag -->
        <input type="checkbox" id="add-task-modal" class="modal-toggle" />
        <div class="modal modal-bottom sm:modal-middle">
            <div class="modal-box relative">
                <form method="POST" id="add-task-form" class="flex flex-col items-center" action="add/">
                    {% csrf_token %}
                    <label id="close-task-modal" for="add-task-modal"
                        class="btn btn-sm btn-circle absolute right-2 top-2 hover:bg-red-500">✕</label>
                    <div class="flex flex-col gap-2 bg-white rounded-xl p-2 sm:p-4 shadow-md w-full sm:w-[90%]">

                        <h1 class="font-bold text-xl text-gray-700 text-center">Add todo</h1>

                        <div class="flex flex-col items-start gap-2 w-full">
                            <label for="id_title" class="font-semibold ml-4">Title</label>
                            <input class="input input-bordered w-full max-w-x z-5" type="text" name="title"
                                maxlength="50" required="" id="id_title" />
                        </div>
                        <div class="flex flex-col items-start gap-2 w-full">
                            <label for="id_description" class="font-semibold ml-4">Description</label>
                            <textarea class="textarea textarea-bordered w-full z-5" name="description" cols="40"
                                rows="10" maxlength="1000" required="" id="id_description"></textarea>
                        </div>

                    </div>
                    <div class="modal-action">
                        <input class="btn w-[100px] mt-4" type="submit" name="submit" value="Create">
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock content %}