example_app/urls.py
from django.urls import path
from example_app.views import index

app_name = 'example_app'

urlpatterns = [
    path('', index, name='index'),
]

katalog/urls.py
from django.urls import path
from katalog.views import show_katalog

app_name = 'katalog'

urlpatterns = [
    path('', show_katalog, name='show_katalog'),
]

mywatchlist/urls.py
from django.urls import path
from mywatchlist.views import *

app_name = 'mywatchlist'

urlpatterns = [
    path('html/', show_mywatchlist, name='show_mywatchlist'),
    path('json/', show_mywatchlist_json, name='show_mywatchlist_json'),
    path('xml/', show_mywatchlist_xml, name='show_mywatchlist_xml'),
]

project_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('example_app.urls')),
    path('katalog/', include('katalog.urls')),
    path('mywatchlist/', include('mywatchlist.urls')),
    path('todolist/', include('todolist.urls')),
]

todolist/urls.py
from django.urls import path
from todolist.views import *

app_name = 'todolist'

urlpatterns = [
    path('', show_todolist, name='show_todolist'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('create-task/', create_task, name='create_task'),
    path('change-task/<int:task_id>', change_task, name='change_task'),
    path('delete-task/<int:task_id>', delete_task, name='delete_task'),
    path('json/' , show_task_json, name='json'),
    path('add/', add_task_ajax, name='add'),
    path('delete/<int:task_id>', delete_task_ajax, name='delete'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en" data-theme="cupcake">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <!-- <link rel="stylesheet" href="{% static 'css/style.css' %}"> -->
  <link href="https://cdn.jsdelivr.net/npm/daisyui@2.31.0/dist/full.css" rel="stylesheet" type="text/css" />
  <script src="https://cdn.tailwindcss.com"></script>
  {% block meta %}
  {% endblock meta %}
</head>

<body class="min-h-screen w-full">
  <div class="navbar bg-base-300">
    <div class="navbar-start">
      <div class="dropdown">
        <label tabindex="0" class="btn btn-ghost lg:hidden">
          <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h8m-8 6h16" />
          </svg>
        </label>
        <ul tabindex="0" class="menu menu-compact dropdown-content mt-3 p-2 shadow bg-base-100 rounded-box w-52">
          <li><a href="{% url 'todolist:show_todolist' %}">Todolist</a></li>
          <li tabindex="0">
            <a class="justify-between">
              Koleksi Tugas
              <svg class="fill-current" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
                <path d="M8.59,16.58L13.17,12L8.59,7.41L10,6L16,12L10,18L8.59,16.58Z" />
              </svg>
            </a>
            <ul class="p-2 z-50 bg-base-300">
              <li><a href="{% url 'katalog:show_katalog' %}">Katalog</a></li>
              <li><a href="{% url 'mywatchlist:show_mywatchlist' %}">Watchlist</a></li>
              <li><a href="{% url 'todolist:show_todolist' %}">Todolist</a></li>
            </ul>
          </li>
        </ul>
      </div>
      <a class="btn btn-ghost normal-case text-xl" href="{% url 'example_app:index' %}">NeoZap's PBP</a>
    </div>
    <div class="navbar-center hidden lg:flex">
      <ul class="menu menu-horizontal p-0">
        <li><a href="{% url 'todolist:show_todolist' %}">Todolist</a></li>
        <li tabindex="0">
          <a>
            Koleksi Tugas
            <svg class="fill-current" xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24">
              <path d="M7.41,8.58L12,13.17L16.59,8.58L18,10L12,16L6,10L7.41,8.58Z" />
            </svg>
          </a>
          <ul class="p-2 w-full bg-base-300 z-50">
            <li><a href="{% url 'katalog:show_katalog' %}">Katalog</a></li>
            <li><a href="{% url 'mywatchlist:show_mywatchlist' %}">Watchlist</a></li>
            <li><a href="{% url 'todolist:show_todolist' %}">Todolist</a></li>
          </ul>
        </li>
      </ul>
    </div>
    <div class="navbar-end pl-2">
      {% block logout %}
      {% endblock logout %}
    </div>
  </div>
  {% block content %}
  {% endblock content %}
</body>

</html>